services:
  web:
    build:
      context: frontend
    ports:
      - 5173:5173
    depends_on:
      - backend
    networks:
      - docker_network

  backend:
    build:
      context: ./backend
      args:
        FASTAPI_PORT: ${FASTAPI_PORT:-8080}
    env_file:
      - ./.env
    ports:
      - "${FASTAPI_PORT}:${FASTAPI_PORT}"
    volumes:
      - ./backend:/app
    networks:
      - docker_network

  db:
    image: postgres:15
    container_name: ${POSTGRES_CONTAINER_NAME}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    env_file:
      - ./.env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - docker_network

networks:
  docker_network:
    name: docker_network
